### ISSUE TITLE
Joda Time converter should be built-in [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#404]
This is [Issue 404](http://code.google.com/p/morphia/issues/detail?id=404) moved from a Google Code project.
Added by 2012-04-14T08:36:25.000Z by [ceefour666@gmail.com](http://code.google.com/u/ceefour666@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low

### Original description

    Joda Time converter should be built-in
    
    related issue: https://github.com/soluvas/morphia/issues/5

**Comment by lewis-almeyda** [comment]
Hi:

I'm trying to use morphia but also need joda-time, any news about this issue??

**Comment by Eemuli** [comment]
I agree with YulawOne, joda-time shouldn't be built-in due to extra dependency.

BUT
since joda-time is still widely used morphia converters are the way to go. Check this out: https://github.com/Eemuli/morphia-jodatime-converter
Just use the converters tag on the entities where you need joda-time. Check out the tests for an example.

**Comment by evanchooly** [comment]
related #940

**Comment by evanchooly** [comment]
closing in favor of #940
