### ISSUE TITLE
add natural order support

### ISSUE THREAD

**Issue by evanchooly** [mongodb/morphia#499]
http://docs.mongodb.org/manual/reference/operator/natural/#op._S_natural

**Comment by cstrempfer** [comment]
I could add an solution for that to pull request https://github.com/mongodb/morphia/pull/1043. Should there be explicit methods for that, e.g. `Sort#ascendingNatural()`, or is adding a constant `NATURAL` to the `Sort` class enough? I prefer the first option, because the constant could easily be missed by developers.

**Comment by evanchooly** [comment]
I favor the explicit methods, too, though I wonder if `naturalAscending()` and `naturalDescending()` might be better.  Either way is probably, fine, though.  As for the package issue, I think a new `Sort` should be added outside the `aggregation` package.  I'd use `order` rather than `direction`.  The aggregation package's Sort would subclass the new one and cast `order` to `int` to preserve the existing API.  Does that make sense?

**Comment by cstrempfer** [comment]
> I'd use `order` rather than `direction`.

Do you talk about the package name? If yes, I move it to `order`. If not, is the `utils` package, ok?

> The aggregation package's Sort would subclass the new one and cast `order` to `int` to preserve the existing API.

What's the `order` part? I cannot find an `order` class in the master branch. Do you mean creating a new enum for the direction?
