### ISSUE TITLE
Investigate ordering text search by $score and including the return value

### ISSUE THREAD

**Issue by evanchooly** [mongodb/morphia#799]
See [this](https://stackoverflow.com/questions/30709505/include-score-in-morphia-full-text-search/30738588) stackoverflow post for a more complete discussion.  Essentially, it would be nice to be able to include the $score values on the returned entity objects after a text search.

More important, however, is being able to order by those scores.

**Comment by ctmay4** [comment]
Thanks for looking into this.

I think the real issue is to add support for $meta (http://docs.mongodb.org/manual/reference/operator/projection/meta/). 

The name of the property ("score" in my example) is defined by the caller as a map to the $meta field.  In Morphia, that field would need to exist in entity obviously.

```java
    BasicDBObject meta = new BasicDBObject("$meta", "textScore");
    BasicDBObject score = new BasicDBObject("score", meta);
```

**Comment by ctmay4** [comment]
Any chance this issue could be looked at for a future release.  I keep running into it an I have to solve it the same way each time.

Instead of just being able to say

```java
    Query<NdcProduct> q = ...
    q.order(...);
    return q.asList();
```

This code is required to return full text results ordered by score.

1. Build my original query in Morphia

    ```java
    Query<NdcProduct> q = ...
    ```

2.  Extract query information into DBObjects so I can sort by score.

    ```java
    // need to build the score for sorting purposes
    BasicDBObject meta = new BasicDBObject("$meta", "textScore");
    BasicDBObject score = new BasicDBObject("score", meta);

    List<DBObject> results = q.getCollection().find(q.getQueryObject(), score).sort(score);
    ```

3.  Loop over the results and convert them back to my original entities from DBObjects

    ```java
    List<NdcProduct> products = new ArrayList<>();
    for (DBObject obj : results) {
        NdcProduct product = morphia.fromDBObject(ds, NdcProduct.class, obj);

        products.add(product);
    }
    ```

**Comment by IVANOPT** [comment]
@ctmay4 your codes really helps me much. Something I suppose that:

1、A small error in codes (The question you asked in stackoverflow is right: https://stackoverflow.com/questions/30709505/include-score-in-morphia-full-text-search/30738588#30738588) :

```
List<DBObject> results = q.getCollection().find(q.getQueryObject(), score).sort(score);

=>

List<DBObject> results = q.getCollection().find(q.getQueryObject(), score).sort(score).toArray();
```

2、 I suggest to add $meta keyword to full text search function of morphia. @evanchooly
